# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1247216aa6f699d15309c1938c893f4d2b714c45b69e8a5d052088895b7475ea9e77fc5c707baa0891adefe650c2e93902cb403ccc202e3d7f18eef3356a1028

test:
  secret_key_base: c4727b999ba437658c3b5e3169349cbb6464c50277f6fb6a1fd76a6d39b5530d6a0ab8cc01c54d7675b53eb415ec7187955143999b8423a2b7060f71ad8b6041

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
